#!/bin/sh
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

rm -rf build


if [ "$#" -eq 0 ]; then
  build_cmd=""
else
  build_cmd="$@"
fi

if [[ $build_cmd != *"-A Win32"* && -x $(command -v ninja) ]]; then
  set -e
  cmake -B build -S yoga -D CMAKE_BUILD_TYPE=Release -D BUILD_SHARED_LIBS=ON -G Ninja "$build_cmd"
else
  set -e
  cmake -B build -S yoga -D CMAKE_BUILD_TYPE=Release -D BUILD_SHARED_LIBS=ON "$build_cmd"
fi

cmake --build build --config Release
