name: Apple

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-pods:
    name: Lint
    if: ${{ false }} # Apple Build is Broken
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-apple

      - name: pod spec lint
        run: pod spec lint --verbose

  build-sample:
    name: Build (${{ matrix.mode }})
    if: ${{ false }} # Apple Build is Broken
    runs-on: macos-latest
    strategy:
      matrix:
        mode: [Debug, Release]

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-apple

      - name: pod install
        working-directory: ./YogaKit/YogaKitSample
        run: pod install

      # TODO: xcodebuild

  clang-format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: clang-format
        uses: ./.github/actions/clang-format
        with:
          directory: ./YogaKit
